name: AccountChanger
version: '1.2'
main: org.mrxzac.accountChanger.AccountChanger
api-version: '1.20'
depend: [ ProtocolLib ]
commands:
  accountchanger:
    description: Reloads the AccountChanger's configuration.
    aliases: [ac]
    permission: accountchanger.base
    permission-message: You don't have permission to use this command.
permissions:
  accountchanger.base:
    description: Allows the user to reload the plugin configuration.
    default: true
  accountchanger.reload:
    description: Allows the user to reload the plugin configuration.
    default: op
  accountchanger.switch:
    description: Allows the user to reload the plugin configuration.
    default: true
  accountchanger.clear:
    description: Allows the user to clear the status for themselves.
    default: true
  accountchanger.clear.all:
    description: Allows the user to clear the status for certain player.
    default: op
  accountchanger.original:
    description: Allows the user to clear the status for themselves.
    default: op
  accountchanger.alias:
    description: Allows the user to clear the status for themselves.
    default: op